"""Add description to Menu

Revision ID: 21e293977a75
Revises: 943d446843d3
Create Date: 2025-07-22 11:21:07.165510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e293977a75'
down_revision = '943d446843d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('food_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
