"""Add food_description to Meal

Revision ID: 943d446843d3
Revises: a3dfc869809e
Create Date: 2025-07-22 11:18:22.320569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943d446843d3'
down_revision = 'a3dfc869809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_description', sa.String(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('food_description')

    # ### end Alembic commands ###
